---
title: "README"
author: "Jordan S Read"
package version: "`r as.character(packageVersion('dinosvg'))`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  md_document:
    variant: markdown_github
---
#`dinosvg` package version `r packageVersion('dinosvg')`

### purpose of package

### rendering svgs

create a plot with `gsplot`
```{r}
library(gsplot)
gs <- gsplot() %>% 
  points(y=1:11, x=1:11, 
           col="blue", pch=18, xlab='pizza', ylab='dogs') %>% 
  points(x=4:11, y=11:4, 
           col="red", pch=1) %>% 
  points(3:5,4:6,side=c(1,4), col='green', pch=14, ylab='cats') %>% 
  lines(2:4, c(2,2.6,2.3), col='blue')
gs
```

```{r, results='asis'}
library(dinosvg)
gs <- gsplot() %>% 
  points(y=1:11, x=1:11, 
           col="blue", pch=18, hovertext=paste0('text:',1:11), xlab='pizza', ylab='dogs', 
           id=paste0('point',1:11), 'fill-opacity'='0.3', 'stroke-opacity'=seq(0,1, length.out = 11)) %>% 
  points(x=4:11, y=11:4, 
           col="red", pch=1, hovertext=paste0('text:',11:4)) %>% 
  points(3:5,4:6,side=c(1,4), col='green', hovertext='green', pch=14, ylab='cats') %>% 
  lines(2:4, c(2,2.6,2.3), col='blue')
cat(svg(gs, as.string=TRUE))
```